# Generated by Django 2.1.1 on 2018-09-05 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_movie_trailer_link'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ['-year']},
        ),
    ]
